### ISSUE TITLE
What is "Failed to fetch updates"?

### ISSUE THREAD

**Issue by Daniyar111** [telegraf/telegraf#1023]
I got this error, even I'm not using bot.
`Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot......botToken......./getUpdates?offset=0&limit=100&timeout=30 failed, reason: read ECONNRESET`
**What is it? And how can I turn off it? In what kind of reason it can be?**
**UPDATED**: I got this error after some moment of sending message from another program side of api: 
```
const Telegraf = require('telegraf');
const bot_token = config.get('telegram.bot-token');
const bot = new Telegraf(bot_token);
```
And I send message like this -> 
```
bot.telegram.sendMessage(adminChannelId, orderMessage, {parse_mode: "HTML"});
return jsonPreProcessor.success({payment: payment, orderArrivals: orderArrivals});
```
Is it normal? Or I did something wrong? Telegram bot is starting from server.js with bot.launch();

**Comment by sagadav** [comment]
this error may be due to blocking Telegram in the country, try using a VPN.

**Comment by MikeMajara** [comment]
@sagadav is there any way to verify this?

I checked doing a curl https://api.telegram.org/bot\<token\>/getUpdates, and it works from both the docker and the server itself.

**Comment by JanneckLange** [comment]
`Failed to fetch updates. Waiting: 1s request to https://api.telegram.org/bot<token>/getUpdates?offset=312416020&limit=100&timeout=30 failed, reason: getaddrinfo EAI_AGAIN api.telegram.org`
Sometimes the reason is ` reason: read ETIMEDOUT`

My code works normal, but there are also update problems. There is no datetime logged with this message. 
The fetch update must be triggered by telegraf itself.

![2020-10-11 14_14_42-Window](https://user-images.githubusercontent.com/26873867/95678346-658e7180-0bcc-11eb-9576-eabd3a889ff0.png)

**Comment by KnorpelSenf** [comment]
Any updates on this?

**Comment by wojpawlik** [comment]
It's probably a temporary Bot API issue (unless it's not temporary), nothing to worry about.

**Comment by JasurJamolovdev** [comment]
this is big problem
