### ISSUE TITLE
Async/Await in Webhook updates

### ISSUE THREAD

**Issue by Geebrox** [telegraf/telegraf#1167]
Hello. I am trying to send a chain of messages using `async/await` but the order of messages coming wrongly. Messages' queue is lost.

Code:
```
bot.command('start', async (ctx) => {
  await ctx.reply('Message #1')
  await ctx.reply('Message #2')
  await ctx.reply('Message #3')
  await ctx.reply('Message #4')
  return ctx.reply('Message Last')
})
```
Result:
![image](https://user-images.githubusercontent.com/15965924/97405826-15c4df80-191a-11eb-815e-e026020dd1a9.png)

Disabling `webhookReply` solves this problem, but what does it mean, could someone explain what is `webhookReply` and what will happen if I disable it? Will it cause on bots performance?

**More info about my configs**:
Telegraf version: `^3.38.0`
Bot updates type: `Webhook`

Thank you!

**Comment by Geebrox** [comment]
More testings:

Code:
```
bot.command('start', async (ctx, next) => {
  await ctx.reply('Message -> 1')
  await ctx.reply('Message -> 2')
  return next()
})

bot.command('start', async (ctx) => {
  await ctx.reply('Message -> 3')
  await ctx.reply('Message -> 4')
  return ctx.reply('Message Last')
})
```

Result:
![image](https://user-images.githubusercontent.com/15965924/97408069-6ab62500-191d-11eb-8230-03252d53b464.png)

**Comment by Geebrox** [comment]
## Performance check:

### **Code:**
```
const { BotController } = require('./controllers')

const { bot } = (botController = new BotController())

bot.command('start', async (ctx, next) => {
  console.time('/start response took')
  await ctx.reply('Message -> 1')
  await ctx.reply('Message -> 2')
  return next()
})

bot.command('start', async (ctx) => {
  await ctx.reply('Message -> 3')
  await ctx.reply('Message -> 4')
  console.timeEnd('/start response took')
  return ctx.reply('Message Last')
})

botController
  .start()
  .then(() => console.log('Bot started'))
  .catch(console.error)
```

### **Results:**

**With** `webhookReply: false`:
```
[nodemon] starting `node src/index.js`
Bot started
/start response took: 497.622ms
/start response took: 508.447ms
/start response took: 483.859ms
```

Messages are received in the right order
<details>
  <summary>Show image</summary>
  
  ![image](https://user-images.githubusercontent.com/15965924/97493847-5eff4880-1987-11eb-8272-8634bc11dad2.png)
</details>

**With** `webhookReply: false`:
```
[nodemon] starting `node src/index.js`
Bot started
/start response took: 372.492ms
/start response took: 366.663ms
/start response took: 379.303ms
```

###### Strange
Messages are received in the wrong order, actually, first and second messages from the code are swapped and others are received in the right order.
<details>
  <summary>Show image</summary>
  
  ![image](https://user-images.githubusercontent.com/15965924/97494523-39267380-1988-11eb-9671-d4b50bf172cd.png)
</details>

<hr>

As we can see, bot responses faster when `webhookReply` is enabled, but the first and second message order is changed while answering. The **strangest** part is that other messages order is not changed.
**Please, advise!**

@dotcypress

**Comment by kraftwerk28** [comment]
> could someone explain what is `webhookReply` and what will happen if I disable it? Will it cause on bots performance?

In webhook mode, when there's an update from Telegram side (e.g. new message came to your bot, the Telegram server makes a request to host which you set in webhook. If you make a response to this request (e.g. send some message in response to `/start` command), you can either send a **new** request to Telegram server, or **respond** to those request which came to your server. The second way is obviously faster, since there's only one TCP handshake.

Regarding you problem with lost message order, that's because first message is handles "separately", not in `await` sequence, because Telegraf makes webhook reply with it. Others `ctx.reply(...)` come as usual, they are separete requests. I'd recommend either **switching to webhookReply** and making **all bot responses in a single message** or if your bot is designed to respond with multiple messages (e.g. some chat game), place `webhookReply: false` to constructor options.

**Comment by KnorpelSenf** [comment]
@Geebrox please consider closing this issue if your problem was solved
