### ISSUE TITLE
How can bot detect his own messages?

### ISSUE THREAD

**Issue by Erfesto** [telegraf/telegraf#1196]
I'm using "two-part" bot (telethon(python)+telegraf. Same bot token)

Telethon see, when he sends messages, also he see when Telegraf sends messages. But Telegraf - dunno how to do it.
Telegraf sends message -> Telethon see it -> Telethon sends message -> Telegraf must see sended Telethon's message.

```
// sending command /start and telethon reacts on it (bot.py)
@bot.on(events.NewMessage(pattern='/start'))
async def start(event):
    await event.respond('Start command used.')

// and telegraf code... (bot.js)
bot.on('message', (ctx) => {
  if(ctx.message.text != '/start') console.log('Yo!') // ignore my message, search for bot message
  else if(ctx.message.from.is_bot === true || ctx.message.from.is_bot != false) console.log('Yo!') // Not works
  else if(ctx.message.from.first_name != 'my name') console.log('Yo!') // Not works
})

// I know, Telegaf can get his own messages with
bot.on('message', async (ctx) => {
  if(ctx.message.text === 'Test') ctx.reply('I see test').then(res => console.log(res)) // or with variable...
}) // but i need to detect bot message from telethon.
```

Telethon have awesome ability to detect incoming and outgoing messages...if telegraf can't do this - it will be nice when it will be added. Telegraf have really nice features, like "stages", i like it ^^.

P.S
I'm using this hell ("two-part") bot only cause telethon have some features (file downloading, yep). Python "little" hell for me, and have really bad packages for my idea. Sorry, my english is...

**Comment by KnorpelSenf** [comment]
Telegraf and Telethon are fundamentally different. The infrastructure looks like this:
```
( ( ( TELEGRAM ) MTProto API ) HTTP Bot API )
                      ^             ^
                      |             |
                  Telethon       telegraf
```
Telegram is accessed via the MTProto API that is based on the custom protocol with the same name. While it may have advantages for Telegram, it's much more convenient for the masses (aka bot developers) to write bots based on an HTTP interface. That's why they wrapped their API in an HTTP layer. Most of the things you can do via MTProto are also possible via HTTP, but not all of them.

In contrast to `telegraf`, Telethon does not use this layer, which gives it an advantage in terms of functionality, and a disadvantage in terms of higher complexity.

Receiving the messages sent by the bot itself is not supported by the HTTP layer. As a result, telegraf cannot add support for this.

You said that you're using Telethon mainly for file handling. I assume you do this because it doesn't have the file size limitations of `telegraf`. These limitations are imposed on bots by the HTTP wrapper layer. Telegram bots are technically allowed to send and receive files of any size, but the translation between MTProto and HTTP is constraining the file sizes, most likely for performance reasons.

Recently, Telegram announced the Bot API 5.0. Since this version, it is possible to host your own Bot API server, as they released the source code. This basically means that you're running the HTTP wrapper locally on your own server. You can configure new file limits of you want, and simply allow your bot to send files of any size. That way, you can ditch Telethon completely and handle all files through telegraf, no matter the size.

**Comment by KnorpelSenf** [comment]
PS: Check out this part of the docs:
https://core.telegram.org/bots/api#using-a-local-bot-api-server

You may want to take into consideration to run the Bot API in a Docker container instead of building from source code.

**Comment by Erfesto** [comment]
Hmm...thank you for answers. I'm just downloading files from telegram with Telethon (not with "getFile", just downloading files in project folder with "download_file", then bot use downloaded file (load it in site/dropbox/etc)).

**Comment by wojpawlik** [comment]
See #1267. I'm also considering exposing an `EventEmitter` that'd allow to subscribe to all outgoing requests and their responses, but I haven't opened a proposal yet.
