### ISSUE TITLE
Long polling silently hangs or swallows errors

### ISSUE THREAD

**Issue by wojpawlik** [telegraf/telegraf#1234]
1. If we don't await the middleware before fetching further updates, we break
   a) any semblance of sensible update confirming,
   b) [error handling](https://github.com/telegraf/telegraf/blob/bc18691c5c80a27796ef318d65ec431b7280d713/src/core/network/polling.ts#L74-L79) (every error turns into a rejection not handled by Telegraf),
   c) backpressure (bot will fetch updates even when overloaded),
   d) others, see https://github.com/telegraf/telegraf/issues/892#issuecomment-583765906.

2. If we do naively `await` (default behavior before #1224), bot will silently wait forever for handlers that break by never resolving (#735). This behavior is still available when `handlerTimeout === Infinity`, accessing it should probably [emit a warning](https://nodejs.org/api/process.html#process_process_emitwarning_warning_type_code_ctor).

3. In #1224, I changed the default behavior to resolve the promise if processing takes longer than 5 seconds. When phrased this way, the problem is obvious: errors thrown after 5 seconds are swallowed!

I have a suggestion, but it ain't pretty either: **throw** when processing takes longer than `handlerTimeout` (which'd need to be extended to say 30 seconds). Such a drastic change obviously needs to be decided upon before 4.0.

The real solution here would be to fetch updates via WebSocket instead, which could allow confirming on per-update basis.

In the meantime, please use webhook in production if you can (with `webhookReply` disabled: #1082).

**Comment by yeldiRium** [comment]
Why resolve the promise after a timeout at all?

If a handler does not resolve, that is a bug on the side of the bot developer. I don't think telegraf should try to recover from bugs made by a bot developer.

If the handler resolves (or errors) after a long time, the timeout swallows its results.

I'm sorry to interject since I don't know the history of some linked issues. But the swallowing of errors seems to me to be the result of trying to fix other's mistakes which results in more room for error. Or am I missing something?

**Comment by KnorpelSenf** [comment]
I'd say you're right about this. When the middleware simply does not return, we cannot do much about it. It's upon the user to handle such a scenario, and that's what we should make possible.

The thing I have in mind is to let the user provide a `timeoutHandler`, i.e. write something like `bot.catchTimeout`. This handler will be supplied with the respective context object that lead to the timeout, and maybe the unresolved `Promise` (not sure about that one yet).

**Comment by KnorpelSenf** [comment]
Here we go.

---

We can solve the problem by introducing a new queue module that tracks all running promises. This is done as follows.

## What we can do about this

The central element of this suggestion is to use a list of promises. Each promise corresponds to one update that was passed to the middleware stack.

When a new update is incoming, the context object is created from it (that's what currently happens in `handleUpdate`). The context object can then be passed to the queue module, which will turn it into a promise by applying it to the middleware stack. The promise is added to the list.

Once the promise resolves or rejects, it is removed from the list again. If it rejects, an error handler is invoked (think: the current `catch`) with both the error and the corresponding context object that led to the error.

If the promise is neither resolved nor rejected before the timeout, it is removed from the promise queue anyway. It can be passed to a second error handler along with its context object. It is upon the user to handle this, e.g. via `catchTimeout`.

## Why this is going to work

Going through the problems mentioned in the issue description above, I'm confident that we can solve every single problem there.

- we do await the middleware, so 1) does not apply
- we do not do this naïvely, so 2) does not apply (the bot won't wait forever for middleware)
- no errors are ever swallowed, so 3) is no longer an issue
- we have a clean way to handle promises that time out
- we do not need websocket support
- we can still track success and failure on a per-update basis
- this works with long polling and webhooks, hence bringing the error handling benefits to both modi

Also, we will basically get a few nice things for free.

- much better performance because we parallelize middleware execution and update polling, so we no longer have to wait for the middleware stack to complete before we can even begin fetching new updates
- basic backpressure support because we can determine the number of running tasks at any point, so the polling mechanism can adjust accordingly and automatically

## What problems we have to solve here

1) We cannot determine whether a promise is actually already resolved or not, at least not as of 2020.
2) We have to find a good data structure. It must support adding an element in `O(1)`. It must support removing an element in an arbitrary position in `O(1)`. It must be possible to determine which promises timed out, and remove them, and this should be in `O(n)` where `n` is the number of promises to remove. If no timeout handler is set, we would actually like to have `O(1)`, so use just constant time for removing `n` promises. This is a common operation because updates are often added in batches.
4) We should avoid starting a timeout for every single incoming update. We should rely on a single timeout can handle all updates.
5) It should be able to automatically pause the polling if a concurrency limit is reached, and the polling should continue afterwards. This should be possible with just minimal changes to the polling module because we don't want to add `pause` and `resume` flags and interrupts etc.

## How we can achieve all of that

I have a nice solution for all of the above, but it makes sense to define two important terms first.

### “Decaying Deque”

A _Decaying Deque_ is a special form of doubly linked list. It has a timestamp for each node, and it is guaranteed to be sorted by these timestamps at all times.

It keeps track of its length at all times.

Usually, deques allow elements to be removed from both sides, but we will rather use it to remove elements from one side, or at arbitrary positions.

It is called decaying deque because you can think of it like we're adding updates to one side, but arbitrary elements are picked out at any time, hence performing a dequeue operation from the centre. The further left an update is, the higher its chance to be removed.

### “Drift”

Once we turn an element (i.e. a context object) into a promise, we don't actually add this to the decaying deque. Instead, we transform it further to a drift. You can think of a drift as a self-removing element of a decaying deque, in other words, just a special form of node in a special form of a linked list.

The intuition behind the word drift is that the promise is _drifting_ to the left in the decaying deque, until it suddenly changes direction and removes itself as soon as its promise completes.

### Everything in operation

A `getUpdates` call fetches 10 updates. They are turned into drifts and added to the tail of the decaying deque. This can be done linearly in the number of updates (10).

```
Previous list:
[]

Next list:
[0,1,2,3,4,5,6,7,8,9]
```

A timeout pointer is set to the _tail_ of the decaying deque. We know that all 10 updates were added in the same instant, so we only need to store one timestamp, remember one element, and start one timer.

```
head          tail   timeout pointer
 |                \ /
 V                 V
[0,1,2,3,4,5,6,7,8,9]
```

When the next batch of updates comes in, it is appended to the decaying deque without moving the timeout pointer.

```
            timeout pointer
                   |
head               |    tail
 |                 |     |
 V                 V     V
[0,1,2,3,4,5,6,7,8,9,a,b,c]
```

If a promise resolves or rejects, it can remove itself from the queue. If the promise resolves that one of the pointers is pointing at, it will have to adjust the respective pointer accordingly. Here, 9 resolved:

```
          timeout pointer
                 |
head             |    tail
 |               |     |
 V               V     V
[0,1,2,3,4,5,6,7,8,a,b,c]
```

If the timeout completes, we know that every element at or left of the timeout pointer are timed out. Hence, we can remove these elements with a single operation. We just set head to the element right of the timeout pointer:

```
    tail        timeout pointer
     |                 |
head |                 |
 |   |                 V
 V   V                null
[a,b,c]
```

If the timeout points to the head, and this element is removed, the timer is cancelled. However, we no longer know how many drifts are to be included in the next batch. In order to avoid a linear search through the list to find out how many updates belong to the batch, we have to have a direct link from the head drift to the rightmost element that was added in the same bulk operation. Consequently, we actually store backward references between the drifts. Note that this optimization is very powerful when many updates time out.

It is also possible to add basic backpressure support. When adding elements to the list, we simply return a promise. If the adding operation still leaves room for more drifts in the decaying deque (length < concurrency limit), the returned promise is resolved immediately. If the concurrency limit was reached, we return an unresolved promise. Whenever drifts are existing the queue, be it from resolving/rejecting or from timing out, they check whether any adding operations returned pending promises, and resolve them if there is space again.

### Drift datatype

It may make things a bit clearer to specify the following.

```ts
interface Drift<T> {
  prev: Drift<T> | null // null for head drift
  next: Drift<T> | null // null for tail drift
  bulk: Drift<T> | null // null iff the last drift in a bulk operation

  elem: Promise<void>
  
  since: Date
  source: T
}
```

## Modularization

It is simple to extract the interface of this module, so we can have competing implementations for this. However, I'm not sure if that is really needed. This suggestion is already extremely efficient and improvements can be made via PR. Given that this is a very integral part of the library, I don't think there's too big of a need for customization. Most people just won't care, so why make this a dependency?

## Related work

I did some research on promise queues, and there are already a number of different ones out there. Some are better and some are worse, but I could not find a single one that can offer what a native implementation can achieve. All of them are slower in some sense, or less flexible, or both. None of them was made for our use case.

Also, I did not find anything that weighs less than 30 kB, and most are rather 120 kB.

It would certainly be nice to simply `npm install` something here and roll with it, but I honestly believe that it will cause us more pain in the long term than writing down the above suggestion ourselves in a day or two.

## Conclusion

I'm intrigued what you all think about this, and I'm happy to answer questions.

I am looking forward to implementing this, but I don't know how long it will take. Also: help appreciated.

**Comment by KnorpelSenf** [comment]
We could even implement partial sorting, i.e. guarantee that updates from the same chat/user/whatever are processed sequentially. This is something we were never able to do before because we did not keep track of when each individual update was done processing!
