### ISSUE TITLE
What are all the "special characters" that need to be escaped, and more importantly, why?

### ISSUE THREAD

**Issue by working-name** [telegraf/telegraf#1242]
Hi there,

When using `{"parse_mode": "MarkdownV2"}` I get an error about `!` and `.` being reserved and they need to be escaped. I'd like to know what all those characters are, and more importantly why are they reserved? What's choking on them - nodejs or telegram's API?

Update: it's telegram's API.
```js
In all other places characters 
'_', '*', '[', ']', '(', ')', '~', '`', '>', 
'#', '+', '-', '=', '|', '{', '}', '.', '!' 
must be escaped with the preceding character '\'.
```

~~Using Markdown parde_mode doesn't issue the same error(s).~~

Thank you!

**Comment by KnorpelSenf** [comment]
Not sure I understand your question correctly, but I'll try. Those characters are part of the Markdown standard. Given that you're already using it here on GitHub, I assume that you're familiar with it.

More specifically, `!` and `.` are used in inlines images and ordered lists, respectively.

However, according to my knowledge, none of these two features are supported by Telegram, so I assume they just included it in order to comply with the convention, or perhaps because they wanted to use an existing rendering library.

Here are examples of for the two characters.

Inline image:
```md
![Image](https://source.unsplash.com/0AyNJh3Razo)
```
![Image](https://source.unsplash.com/0AyNJh3Razo)

Ordered list:
```md
1. Foo
1. Bar
5. Baz
```
1. Foo
1. Bar
5. Baz

**Comment by working-name** [comment]
@KnorpelSenf Thank you, very kind of you to explain markdown. You're a great teacher!

But no, their API does not implement inline images or anything like that. It's just a tad too touchy (probably using a less-than-stellar parser) because it reacts with an error to things like a period or exclamation point at the end of a sentence and input. No respectable parser would consider that a marker for a list or start of a (non-implemented) inline image.

This does present a challenge when pulling data from other sources and then having the bot send as a message, especially if that source also uses some markdown. Now I have the choice between coding my own parser or run a bunch of regex replacements while carefully not disturbing valid markdown :)

**Comment by KnorpelSenf** [comment]
That's correct. You may consider changing the markup format to HTML, then your markdown is no issue at all. It makes it a little more cumbersome to highlights things in your text, but at least you don't need to mess around with parsing Markdown then.

**Comment by khalidwaleed0** [comment]
> 
> 
> That's correct. You may consider changing the markup format to HTML, then your markdown is no issue at all. It makes it a little more cumbersome to highlights things in your text, but at least you don't need to mess around with parsing Markdown then.

I tried formatting to HTML and it is great, I only needed to encode '&' to %26. Other than that it is perfect.

**Comment by chrisspiegl** [comment]
Possibly also a solution would be to use your own markdown parser and then send as html:

Note that the `marked.parseInline` is used because it would otherwise wrap all the paragraphs in `<p></p>` tags which are unsupported by Telegram.

```js
import { marked } from 'marked'
bot.help((ctx) => {
  ctx.replyWithHTML(marked.parseInline(`Hello,

1. Testing
2. This

What?

* a
* list

[test link](https://github.com/telegraf/telegraf/issues/1242) with **BOLD** and _ITALIC_.` , ctx)))
})
```

And will look like:

<img width="593" alt="Capture 2022-02-17 at 12 25 50" src="https://user-images.githubusercontent.com/1096384/154472049-e50e7c3c-2c61-45ad-958f-8920902c84ce.png">

**Comment by dawadam** [comment]
I like this little hack, thanks @chrisspiegl

**Comment by Kikobeats** [comment]
Hello, this is my workaround:

```js
// https://core.telegram.org/bots/api#markdownv2-style

const SPECIAL_CHARS = [
  '\\',
  '_',
  '*',
  '[',
  ']',
  '(',
  ')',
  '~',
  '`',
  '>',
  '<',
  '&',
  '#',
  '+',
  '-',
  '=',
  '|',
  '{',
  '}',
  '.',
  '!'
]

const escapeMarkdown = (text) => {
  SPECIAL_CHARS.forEach(char => (text = text.replaceAll(char, `\\${char}`)))
  return text
}
```

I hope it could be useful for more users 🙂

**Comment by Wafiismail27** [comment]
> Hello, this is my workaround:
> 
> ```js
> // https://core.telegram.org/bots/api#markdownv2-style
> 
> const SPECIAL_CHARS = [
>   '\\',
>   '_',
>   '*',
>   '[',
>   ']',
>   '(',
>   ')',
>   '~',
>   '`',
>   '>',
>   '<',
>   '&',
>   '#',
>   '+',
>   '-',
>   '=',
>   '|',
>   '{',
>   '}',
>   '.',
>   '!'
> ]
> 
> const escapeMarkdown = (text) => {
>   SPECIAL_CHARS.forEach(char => (text = text.replaceAll(char, `\\${char}`)))
>   return text
> }
> ```
> 
> I hope it could be useful for more users 🙂

Thank you, it was very useful for me!

**Comment by bennycode** [comment]
@MKRhere how about adding a util method to `telegraf` to share the Markdown escaping? This would be really helpful for bot developers.

**Comment by MKRhere** [comment]
@bennycode

* I'd generally not advice escaping unless you absolutely need it. However, I recently did publish a module: [@telegraf/entity](https://github.com/telegraf/entity) which has escapers for Markdown and HTML.
* I'd recommend using fmt helpers [(see docs)](https://github.com/feathers-studio/telegraf-docs/blob/b694bcc36b4f71fb1cd650a345c2009ab4d2a2a5/guide/%3F%3F%3F-formatting.md#fmt) since Telegraf 4.11+.

**Comment by bennycode** [comment]
Thanks for your reply and suggesting to use `telegraf/format`. I really like the idea of it and agree that it would be the best formatting option when using Telegram. 

However, I am writing an application where texts are send through multiple messengers (Telegram, Slack, Wire, ...) and I would like to send Markdown to all of them (as they can handle it). Using the fmt helper would make my source texts heavily dependant on Telegram and not be versatile anymore for other messengers.

**Comment by MKRhere** [comment]
In that case use `@telegraf/entity`:

```TS
import { escapers } from "@telegraf/entity";

escapers.HTML(text); // HTML escaped text
escapers.MarkdownV2(text); // escaped for Telegram's MarkdownV2
```

**Comment by bennycode** [comment]
Thanks for the hint. I was surprised that this doesn't become bold:

```ts
const text = '**Make this BOLD.**';
ctx.replyWithMarkdownV2(text);
```

So I installed `@telegraf/entity` and tried using:

```ts
const text = '**Make this BOLD.**';
const markdown = escapers.MarkdownV2(text);
ctx.replyWithMarkdownV2(markdown);
```

It actually turned `**Make this BOLD.**` into `\*\*Make this BOLD\.\*\*` but when sending the message, the text didn't became bold. That's why I am now using your workaround with `marked`:

```ts
const text = '**Make this BOLD.**';
const html = await marked.parseInline(text);
ctx.replyWithHTML(html);
```

This works for me. 👍

**Comment by MKRhere** [comment]
@bennycode That's because Telegram Markdown wants `*bold*` and `_italic_`, not `**bold**`. Read the [docs](https://core.telegram.org/bots/api#formatting-options). The escaper is doing exactly what an escaper must do - make special (formatting) characters not do anything special.

**Comment by bennycode** [comment]
@MKRhere I have read the docs and Telegram states that `**bold**` is supported: 

<img width="459" alt="image" src="https://github.com/telegraf/telegraf/assets/469989/4a972807-c961-4850-8a42-9ea65b4c2d6e">

Source: https://core.telegram.org/api/entities#allowed-entities

When writing `Hello **BotFather**` in Telegram chat (app), it also becomes bold.

**Comment by MKRhere** [comment]
Refer only to the Bot API docs when working with bots:

![image](https://github.com/telegraf/telegraf/assets/19621208/85044492-6198-4fc8-99ea-0de869192cd9)

Source: https://core.telegram.org/bots/api#markdownv2-style

**Comment by bennycode** [comment]
Makes sense. I was just not expecting Telegram to have such rendering inconsistencies depending on the endpoint being used. Now I know this important detail. Thanks for sharing.

**Comment by KnorpelSenf** [comment]
It's not just the endpoint that differs, it's a completely different API. You were reading the docs for Telegram Clients, not for bots. But yes, it's still a bit confusing that they chose to implement two different markdown flavours.

**Comment by teoring** [comment]
> ```ts
> await marked.parseInline(text);
> ```

This didn't work for me for some reason..
