### ISSUE TITLE
bot.on Parameters

### ISSUE THREAD

**Issue by VenRoot** [telegraf/telegraf#1277]
Good morning everyone,

I've been looking through the Telegram API... the Telegraf Docs... but I couldn't find a list of bot.on() variants...
I got `bot.on('new_chat_members', (e) => Welcome(e));` to welcome new members in my group.

Is there something like a `bot.on('user_left_channel`?
Best would be a whole list with parameter options for bot.on
Can such get added to the docs?

Thank you!

Sincerly
Ven

**Comment by KnorpelSenf** [comment]
All possible fields in an `Update` are allowed, and all possible types of `Message`s, confer https://core.telegram.org/bots/api#update.

Currently, this is only “documented” by TypeScript types. If you're installing the library from source (`npm i telegraf/telegraf`), your code editor should autocomplete the list of possible options for you.

We're moving to `typedoc` (tracked by #1205) which generates documentation from the source code and hence the docs will hopefully be up to date as soon as the 4.0 release is shipped. Note that this release is immanent. The code is complete, we're hoping to get the last PR merged today, so I don't think it's going to take more than a few days before it can be published (no promise, I don't have publish permissions myself).

We therefore won't write this documentation manually.

**Comment by KnorpelSenf** [comment]
Also, `user_left_channel` cannot be provided because Telegram generally does not notify bots about users how join or leave a channel. If your bot does not receive an `Update` about it, Telegraf can of course not handle it. Consider using a readonly group chat instead.

Btw, the up to date list of options for `bot.on` is [here in the code](https://github.com/telegraf/telegraf/blob/develop/src/context.ts) (`UpdateTypes` and `MessageSubTypes`).

**Comment by VenRoot** [comment]
Well, `left_chat_member` worked for my supergroup! Thank you for your work, and thanks for providing the code, I'm already excited for 4.0! The project is just great. Keep it up!
