### ISSUE TITLE
Bot can't receive messages in groups

### ISSUE THREAD

**Issue by mhmyesman** [telegraf/telegraf#1335]
## Context

I'm trying to make a bot that replies to commands and the like. Everything works just fine messaging the bot directly, but outside of direct messages it doesn't receive messages. It's the same issue as #134 and #437, but setting ``bot.options.username = botInfo.username`` after initializing with ``const bot = new Telegraf(config.API_TOKEN, {username: 'MyBot'})`` doesn't fix my issue. I've made sure that group privacy settings are disabled, meaning the bot will receive every message, and I gave my bot all permissions. Reinstalled Telegraf. No luck.

bot.hears, bot.on, bot.command all don't get called. 

* Telegraf.js Version: 4.0.2
* Node.js Version: 14.15.4
* Operating System: Windows 10

## Minimal Example Code Reproducing the Issue

```js
const bot = new Telegraf(config.API_TOKEN, {
  username: 'MyBot'
})

bot.command('command', (ctx) => {
  ctx.reply('received command')
})

bot.telegram.getMe().then((botInfo) => {
  bot.options.username = botInfo.username
})

bot.launch()
```

## Expected Behavior

Bot receives messages in group chats with my set up. 

## Current Behavior
Bot doesn't receive messages outside DMs. 

No errors.

**Comment by Autapomorph** [comment]
First, you may want to use `botInfo.username` instead of just `username` ([see](https://github.com/telegraf/telegraf/blob/57f16c70901e3c73b9ab67933a926fedf7a2b11d/src/telegraf.ts#L68))
Second, in `v4` you can omit setting bot info manually ([see](https://github.com/telegraf/telegraf/blob/57f16c70901e3c73b9ab67933a926fedf7a2b11d/src/telegraf.ts#L152))
Third, bot group messages works just fine for me with your exact code snippet, so you're doing smth wrong, either with bot group settings or token, or maybe you send just `command` to your group chat (according to your code you need to send `/command`, note first slash) or whatever else

**Comment by mhmyesman** [comment]
Hey,

Thanks for the comprehensive answer. I send ``/command``, not ``command``. If it works for you, there's probably something I messed up -- thank you for trying out my code. I'll keep this issue open for the time being, so I can follow up in case I figure out what I did wrong with my set up. 

Thanks again.

**Comment by mhmyesman** [comment]
Nope, still haven't figured it out. I'll just take the blame for this one and say I probably messed something up.

Thanks for your help @Autapomorph.

**Comment by eEQK** [comment]
if you've disabled privacy after adding bot to the group, you have to kick it and add it again
