### ISSUE TITLE
Question | Property 'data' does not exist on type 'CallbackQuery'

### ISSUE THREAD

**Issue by Keller18306** [telegraf/telegraf#1471]
How to fix that?
![image](https://user-images.githubusercontent.com/23178771/121821317-f4461780-cca0-11eb-882b-5c6949970c34.png)
![image](https://user-images.githubusercontent.com/23178771/121821347-1dff3e80-cca1-11eb-8132-258f35a9b2c8.png)

**Comment by wojpawlik** [comment]
Related: #1388

Ideally, there should be `Composer.dataQuery` and `Composer::dataQuery`; PR welcome.

**Comment by ghost** [comment]
Have a same issue.
Can use:
interface Callback {
    data: string;
}

let callback = ctx.callbackQuery as Callback;

**Comment by crossonym** [comment]
Can use:
 interface Callback {
    data: string;
}

let callback = ctx.callbackQuery as Callback;

**Comment by Keller18306** [comment]
> Related: #1388
> 
> `Composer.dataQuery` and `Composer::dataQuery`

I did not find this

**Comment by wojpawlik** [comment]
Because they don't exist.

Alternatively, I consider it a bug that `Composer.action` and `Composer::action` match game queries.

**Comment by kirofint** [comment]
Я пока использую `ctx.callbackQuery?.['data']` чтобы избежать ошибки

**Comment by MKRhere** [comment]
The original problem here is that callbackQuery could be either DataQuery or GameQuery, and until you narrow it down, TypeScript doesn't know which one it is. Since version 4.11.0, there's a builtin module called filters. Read [release notes](https://github.com/telegraf/telegraf/releases/tag/v4.11.0) to learn about filters.

In short, you can now do:

```TS
import { callbackQuery } from "telegraf/filters";

bot.on(callbackQuery("data"), ctx => {
  ctx.callbackQuery.data // all good!
});

bot.on(callbackQuery("game_short_name"), ctx => {
  ctx.callbackQuery.game_short_name // all good!
});
```

This is very convenient! But you can also do this if you need, since the same release:

```TS
bot.on("callback_query", ctx => {
  if (ctx.has(callbackQuery("data"))) {
    ctx.callbackQuery.data // works!
  } else {
    ctx.callbackQuery.game_short_name // works!
  }
});
```

I'm closing this issue as completed, since the new method allows filtering very specific queries.
