### ISSUE TITLE
Error handling not working

### ISSUE THREAD

**Issue by andrey-hohlov** [telegraf/telegraf#155]
Hi!

In my case users can create bot and set channels for it (Slack, Telegram and other).
This is module for Telegram channel:
```javascript
function init(bot) {
  const app = new Telegraf(bot.channels.telegram.token);

  app.on('text', (ctx) => {
   // Get reply from bot and send it to user
  });

  app.catch((err) => {
   console.log('error', err);
  });

  app.startPolling();

  return app;
}

module.exports = {
  init,
};
``` 

The 'Bot Token is required' error is caught in the higher promise error handler.

If token is wrong there is  'Failed to get updates. Waiting: 1s...' message in console.
But this is not my console.log output.

What I'm doing wrong?

**Comment by ofstudio** [comment]
I't s a god idea to handle connection errors more flexible way (not long reconnection loop)

**Comment by dotcypress** [comment]
@andrey-hohlov `catch` method works only with BOT pipeline, cause Telegraf can work with updates in few ways: long polling/webhook/[`processUpdate`](https://github.com/telegraf/telegraf/blob/develop/docs/telegraf.md#handleupdate)(For example with `processUpdate` BOT can work even without token).

And because network issues sometimes occur with Telegram servers, polling loop use separates error handling approach(with rate limiter support).

@ofstudio current implementation of network error handling is good enough for me, but anyway I'll appreciate any additional input. 👍
