### ISSUE TITLE
Should handle 429 flood wait errors during polling

### ISSUE THREAD

**Issue by phi1ipp** [telegraf/telegraf#1563]
## Context

* Telegraf.js Version: 4.4.2
* Node.js Version: 17.1.0
* Operating System: alpine

## Minimal Example Code Reproducing the Issue

```ts
const { Telegraf } = require('telegraf');

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);

bot.start((ctx) => ctx.reply('Welcome'));

bot.on('text', async (ctx) => { ...
```

Not sure how to reproduce the issue, but here is a stack trace
```
2021-12-30T15:32:31.446352795Z /usr/src/app/node_modules/telegraf/lib/core/network/client.js:263
2021-12-30T15:32:31.446436840Z             throw new error_1.default(data, { method, payload });
2021-12-30T15:32:31.446457232Z                   ^
2021-12-30T15:32:31.446472689Z
2021-12-30T15:32:31.446487615Z TelegramError: 429: Too Many Requests: retry after 5
2021-12-30T15:32:31.446502487Z     at Telegram.callApi (/usr/src/app/node_modules/telegraf/lib/core/network/client.js:263:19)
2021-12-30T15:32:31.446517557Z     at runMicrotasks (<anonymous>)
2021-12-30T15:32:31.446532914Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-12-30T15:32:31.446548317Z     at async Polling.[Symbol.asyncIterator] (/usr/src/app/node_modules/telegraf/lib/core/network/polling.js:27:33)
2021-12-30T15:32:31.446563300Z     at async Polling.loop (/usr/src/app/node_modules/telegraf/lib/core/network/polling.js:69:30) {
2021-12-30T15:32:31.446578644Z   response: {
2021-12-30T15:32:31.446592851Z     ok: false,
2021-12-30T15:32:31.446607299Z     error_code: 429,
2021-12-30T15:32:31.446621857Z     description: 'Too Many Requests: retry after 5',
2021-12-30T15:32:31.446667056Z     parameters: { retry_after: 5 }
2021-12-30T15:32:31.446685253Z   },
2021-12-30T15:32:31.446699808Z   on: {
2021-12-30T15:32:31.446714119Z     method: 'getUpdates',
2021-12-30T15:32:31.446728450Z     payload: { timeout: 50, offset: 462581445, allowed_updates: [] }
2021-12-30T15:32:31.446743346Z   }
2021-12-30T15:32:31.446757413Z }
```

## Expected Behavior

I assume that polling should swallow this 429 and silently continue working after this response from Telegram

**Comment by hypernova7** [comment]
[Check this](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this)
I recommend you use https://npm.im/telegraf-throttler

**Comment by phi1ipp** [comment]
Thank you @hypernova7, will check it. Looks promising from a first glance

**Comment by KnorpelSenf** [comment]
This cannot be solved by throttling. This cannot be solved at all. This error is by definition impossible. This method is specified to not be rate-limited.

Apparently Telegram doesn't follow their own specification, though.

**Comment by KnorpelSenf** [comment]
Also, this certainly isn't a good first issue …

**Comment by phi1ipp** [comment]
@KnorpelSenf , is it not `good` or is not `first`?  :)

If it can't be fixed with throttling, which I'm sorta agree, is there a chance that the package can capture this exception and just retry w/o throwing the exception further?

**Comment by KnorpelSenf** [comment]
This error is explicitly specified not to happen. Telegraf already handles all possible errors correctly. It doesn't make sense to deviate from their specification. I forwarded this issue to Telegram.

It's not a good first issue to work on for any new contributors because this cannot be solved easily. In fact, this might not be possible at all to be solved on our end. It requires some level of understanding about how the Bot API server works, and how it communicates with Telegram via MTProto.

**Comment by KnorpelSenf** [comment]
The idea to suppress all unknown errors is not good. If Telegram is returning unknown data, then something is very, very wrong. Hence, throwing an error is the reasonable thing to do. We really want to know about these things, so ignoring the error is harmful.

Think about it this way: if we hadn't rethrown the error, this issue would've never been opened, so the bug would simply continue to exist :)

**Comment by phi1ipp** [comment]
Gotcha, @KnorpelSenf , I misunderstood the badge totally. 

As for your explanation, it does make sense. And I agree that it's weird for Telegram API to throw 429 on polling, unless you do it weird way (which is probably not likely, assuming your package is widely used, you would've been notified about the issue long time ago).

Interesting thing it didn't happen again to me after that time. 

Anyway, thank you for looking into the issue and providing some feedback! I wish I could help, but it seems like it would a too heavy lift for me :(

**Comment by KnorpelSenf** [comment]
No worries, thanks for the report. I'll keep you posted if the Telegram team reacts to this in any way.

**Comment by KnorpelSenf** [comment]
Apparently the method `getUpdates` is only specified to never return 429 errors during normal operation of the Bot API server. However, it can indeed return 429 when the Bot API server is closing.

Consequently, telegraf should be changed to handle flood wait errors during long polling by checking the error status code for containing 429, and delaying subsequent calls to `getUpdates` by the specified number of seconds.

**Comment by ahmethkablama** [comment]
> [Check this](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this) I recommend you use https://npm.im/telegraf-throttler

I started using it. It worked great for me. Thank you.

I would definitely recommend it to anyone who has this problem. It's easy and I work very well.

**Comment by dscotese** [comment]
@KnorpelSenf I noticed that you have some way to forward issues to Telegram, which suggests that you know more than most, so I wanted to ask if you know how I can handle this situation:

First, Google Bard points out that Telegram can return a 429 error without indicating how long you have to wait.  Under that circumstance, it's not clear how long I should wait before trying again.  The forwards the code is attempting can be done manually.  Here is the whole story:

I wrote a user bot to forward messages from one chat to another at the rate of one message per second because I kept getting FLOOD_WAIT exceptions requiring 8 - 9 second waits before I added the one-second wait.  After I added it, it was running just fine and I went to sleep.  It forwarded about two or three thousand messages, recovering nicely from "Network down" and "Connection lost" , "Task exception was never retrieved", "Request Timed out", and the most common one "socket.send() raised exception."  Over that 9 hours, my code kept recovering from those problems.  I woke up and typed the time (6:37 am) into the console where it was running because the printout wasn't displaying the time and I wanted a marker.  The next thing printed in the console was a a message from my code reflecting a flood_wait of 1386 seconds, or about 23 minutes.  The timestamps in the history of the target chat agree with this wait time, skipping from 6:32 to 6:56.  Amazingly, that is the ONLY Flood_wait message over the entire 9 hours.  About 40 minutes later (7:31), I terminated the bot and restarted it, stupidly failing to update the starting time for the forwarded messages, and so repeated about 400 forwards before realizing my mistake.  It has been about a day and a half since then, I am still unable to get messages earlier than the 2/21/23 message forwarded just before I terminated it.

**Comment by KnorpelSenf** [comment]
> I noticed that you have some way to forward issues to Telegram

What made you believe that? 🤔

**Comment by KnorpelSenf** [comment]
Anyway, there isn't really an issue in your story. You just need to respect flood wait errors and stop waiting for a second. I wrote a good summary for the Bot API once, and it will most likely apply to your use case, as well: https://grammy.dev/advanced/flood

**Comment by dscotese** [comment]
> > I noticed that you have some way to forward issues to Telegram
> 
> What made you believe that? 🤔

"I forwarded this issue to Telegram." (from https://github.com/telegraf/telegraf/issues/1563#issuecomment-1019146393).  Thanks for the article.  I noted "When sending messages inside a particular chat, avoid sending more than one message per second".  Also, one message per second is too much because “Also note that your bot will not be able to send more than 20 messages per minute to the same group.”

Lastly, "Do not ignore 429 errors. (This could lead to a ban.)". If a user bot (no bot_token, just a valid api_hash and  and api_id) does get banned, how would the owner know?
Thanks for your help!

**Comment by KnorpelSenf** [comment]
I literally just ask in the chat around TDLib, which is the library the underpins the Bot API. It's at https://t.me/tdlibchat. 

> how would the owner know

No idea, I did not spam a lot of users yet. If you do that and get banned for it, please let us know!
