### ISSUE TITLE
Property 'wizard' does not exist on type 'Context<Update>'

### ISSUE THREAD

**Issue by grigoryevandrey** [telegraf/telegraf#1730]
## Context

I am getting error that property "wizard" does not exists where it actually should exist. 

* Telegraf.js Version: 4.10.0
* Node.js Version: v16.13.2
* Operating System: Mac OS Monterey 12.2.1

## Minimal Example Code Reproducing the Issue

```ts
import { Telegraf, Context } from 'telegraf';

const bot = new Telegraf('TOKEN');

bot.command('register', (ctx: Context) => {
    ctx.reply('What is your name?');
    ctx.wizard.state.data = {};
    return ctx.wizard.next();
});
```

## Expected Behavior

Type error should not occur

## Current Behavior

Type error occurs: Property 'wizard' does not exist on type 'MatchedContext<Context<Update>, "text">'

## Error Message and Logs

Property 'wizard' does not exist on type 'Context<Update>'

**Comment by MKRhere** [comment]
See the examples for [Wizards](https://github.com/feathers-studio/telegraf-docs/blob/4feffcd893a86ed1fcc761279d17328beb4a2f21/examples/wizards/wizard.ts).

The code you've posted will probably fail, because `ctx.wizard` shouldn't be used outside the context of Wizard itself (for example in `bot.command`).
