### ISSUE TITLE
Problem with catching Telegram error 403

### ISSUE THREAD

**Issue by kapisolec** [telegraf/telegraf#1757]
### Discussed in https://github.com/telegraf/telegraf/discussions/1756

<div type='discussions-op-text'>

<sup>Originally posted by **kapisolec** December  6, 2022</sup>
Hello, I would like to ask is there a way to globally catch **all** the errors regarding requests/responses that Telegram sends? I have multiple scenes with many answers and dialogue decisions and I can't really think of a better way of catching all the errors than doing it globally. I tried doing this: 
```
process.on("uncaughtException", (err) => {
  console.log(err);
});

process.on("unhandledRejection", (err) => {
  console.log(err);
});

bot.catch((err, ctx) => {
  console.log(err, ctx);
});
```

But it doesn't seem to work properly, there is a certain type of request/response that I can't catch. This is the error for it:
```
Unhandled error while processing {
  update_id: <id>,
  my_chat_member: {
    chat: {
      id: <id>,
      first_name: '<name>',
      username: '<name>',
      type: 'private'
    },
    from: {
      id: <id>,
      is_bot: false,
      first_name: '<name>',
      username: '<name>',
      language_code: 'en'
    },
    date: 1670331646,
    old_chat_member: { user: [Object], status: 'member' },
    new_chat_member: { user: [Object], status: 'kicked', until_date: 0 }
  }
}
TelegramError: 403: Forbidden: bot was blocked by the user
    at Telegram.callApi (/<path>/node_modules/telegraf/lib/core/network/client.js:291:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async execute (/<path>/node_modules/telegraf/lib/composer.js:471:17)
    at async /<path>/node_modules/telegraf/lib/composer.js:472:21
    at async execute (/<path>/node_modules/telegraf/lib/composer.js:471:17)
    at async /<path>/node_modules/telegraf/lib/composer.js:472:21
    at async execute (/<path>/node_modules/telegraf/lib/composer.js:471:17)
    at async execute (/<path>/node_modules/telegraf/lib/composer.js:471:17)
    at async /<path>/node_modules/telegraf/lib/composer.js:472:21 {
  response: {
    ok: false,
    error_code: 403,
    description: 'Forbidden: bot was blocked by the user'
  },
  on: {
    method: 'sendMessage',
    payload: { chat_id: <id>, text: 'Choose an option' }
  }
}

```

All the other errors are caught just fine. Also I dont know where `old_chat_member` and `new_chat_member` comes from - bot can't be used in the groups so it shouldn't appear. </div>

**Comment by MKRhere** [comment]
> is there a way to globally catch all the errors regarding requests/responses that Telegram sends

Short answer: `bot.catch` is the correct way and you must await all API calls / promises.

Long answer:

There are two places where you could handle errors.

One is for errors that can happen while handling an update. This also includes any `ctx.reply()` / `ctx.telegram.sendMessage()` you may call within the handlers, BUT remember that you HAVE to await or return these calls. Otherwise Telegraf has no way to handle them. Example:

```TS
const bot = new Telegraf(token);

bot.hears("Hello", async ctx => {
	ctx.reply("Hello!"); // ❌ BAD
	await ctx.reply("Hello!"); // ✅ Good!
});

bot.catch(err => {
	// handle error
});

bot.launch();
```

This is where your error could be caught!

---

The other place you can handle errors is if polling itself errors.

```TS
bot.launch().catch(err => {
	// "handle" error
});
```

Remember that if an error is thrown here, it's fatal. Even if you catch the error, the bot will have stopped. It's possible for many reasons: bad token, another bot is already using this token, network error, and so on. In all of these cases, the bot could not continue running. This is only provided for users who don't want their process to crash because the bot errored. In most cases, it's preferable for the bot to crash and safely restart, and you should not use this unless you know you need it.

You probably should not use `process.on("uncaughtException",` either. I assume your problem was simply not awaiting your promises. That should resolve it.

**Comment by bek-shoyatbek** [comment]
@MKRhere  bot.catch() with await ctx.reply()....
