### ISSUE TITLE
bot.on() method bug

### ISSUE THREAD

**Issue by manasseh-fikadu** [telegraf/telegraf#1766]
## Context
* Telegraf.js Version: 4.11.2
* Node.js Version: 16.13.0
* Operating System: Windows

## Minimal Example Code Reproducing the Issue

```js
bot.command("translate", (ctx) => {
  // type in any text the bot will detect the language and translate to your target language
  const outerContext = ctx;
  ctx.reply("Type in any text to translate");

  // get the text from the user
  bot.on("text", async (ctx) => {
    const text = ctx.message.text;
    // get the language code by awaiting on the detect function
    const language = await api.detect(text);
    console.log(language);
    const detectedLanguage = Object.keys(languageCodeMapping).find(
      (key) => languageCodeMapping[key] === language
    );

    ctx.reply(`The detected language is ${detectedLanguage}`);
    ctx.reply("Choose the target language", {
      reply_markup: {
        keyboard: [
          ["english", "chinese", "french", "german", "italian"],
          ["japanese", "korean", "portuguese", "russian", "spanish"],
          ["amharic", "hindi", "arabic", "turkish", "greek"],
        ],
        one_time_keyboard: true,
      },
    });    
    bot.on("text", async (ctx) => {
      const targetLanguage = ctx.message.text;
      const translated = await api.translate(
        language,
        languageCodeMapping[targetLanguage],
        text
      );
      ctx.reply(`${translated}`);
    });
  });
});
```

## Expected Behavior

This was supposed to move on to the next prompt after the user entering the target language

## Current Behavior

Stuck inside a loop prompting the user again and again for the target language

## Additional

When I looked at the internal implementation of `bot.on()` it has I think a conflicting namespace.

`
on<Filter extends tt.UpdateType | Guard<C['update']>>(
    filters: MaybeArray<Filter>,
    ...fns: NonemptyReadonlyArray<Middleware<FilteredContext<C, Filter>>>
  ): this

 
   * Registers middleware for handling updates narrowed by update types or message subtypes.
   * @deprecated Use filter utils instead. Support for Message subtype in `Composer::on` will be removed in Telegraf v5.
   
  on<Filter extends tt.UpdateType | tt.MessageSubType>(
    filters: MaybeArray<Filter>,
    ...fns: NonemptyReadonlyArray<
      Middleware<NarrowedContext<C, tt.MountMap[Filter]>>
    >
  ): this

  on<Filter extends tt.UpdateType | tt.MessageSubType | Guard<C['update']>>(
    filters: MaybeArray<Filter>,
    ...fns: NonemptyReadonlyArray<
      Middleware<
        Filter extends tt.MessageSubType
          ? MatchedContext<C, Filter>
          : Filter extends tt.UpdateType | Guard<C['update']>
          ? FilteredContext<C, Filter>
          : never
      >
    >
  ): this {
    // @ts-expect-error This should get resolved when the overloads are removed in v5
    return this.use(Composer.on(filters, ...fns))
  }
`

In my scenario it is using the deprecated version of it!

**Comment by MKRhere** [comment]
This has nothing to do with the deprecated overload. You should never use a listener inside another listener. Once you attach a `bot.on` listener, it stays on for the lifetime of the bot. Telegraf does not provide a way to stop listening.

The reason for this is that if you remove a listener, on bot restart Telegraf doesn't know what to listen and what not to. In your case, the reverse is true. On a bot restart, Telegraf doesn't know you have extra listeners attached inside listeners.

Since there is no way to stop listening, all nested listeners will keep responding to requests every time. Not only that, but your bot will use more memory each time a listener is added, until it runs out of memory.

To listen for multi-step input, consider Wizard Scenes [(Example)](https://github.com/feathers-studio/telegraf-docs/blob/4feffcd893a86ed1fcc761279d17328beb4a2f21/examples/wizards/wizard.ts).

**Comment by manasseh-fikadu** [comment]
Thank you for the quick response @MKRhere
