### ISSUE TITLE
Bot does not replying

### ISSUE THREAD

**Issue by NekonexDev** [telegraf/telegraf#1808]
## Context

* Telegraf.js Version: latest 4.11.2
* Node.js Version: 16
* Operating System: Linux Ubuntu 20

## Minimal Example Code Reproducing the Issue

```ts
ctx.reply("hello")
```

## Expected Behavior
Replying to message

## Current Behavior
![IMG_20230301_095416](https://user-images.githubusercontent.com/97462968/222065987-69c90a34-af35-4a8c-8368-8086419fde6f.jpg)

## Error Message and Logs (`export DEBUG='telegraf:*'`)
None

**Comment by MKRhere** [comment]
So this has been the behaviour of Telegraf since the beginning, and users are always confused. In Telegraf (and similar frameworks), `ctx.reply` sends a message in the same chat.

In v5 we are changing the behaviour to always reply by default (and ctx.sendMessage) for the current behaviour. You can currently opt-in to this behaviour using this middleware:

```TS
import { useNewReplies } from "telegraf/future";

// ...
bot.use(useNewReplies());

bot.on("message", async ctx => {
	await ctx.reply("Hello!"); // actually replies
});
```

**Comment by NekonexDev** [comment]
> So this has been the behaviour of Telegraf since the beginning, and users are always confused. In Telegraf (and similar frameworks), `ctx.reply` sends a message in the same chat.
> 
> In v5 we are changing the behaviour to always reply by default (and ctx.sendMessage) for the current behaviour. You can currently opt-in to this behaviour using this middleware:
> 
> ```ts
> import { useNewReplies } from "telegraf/future";
> 
> // ...
> bot.use(useNewReplies());
> 
> bot.on("message", async ctx => {
> 	await ctx.reply("Hello!"); // actually replies
> });
> ```

Thanks!
