### ISSUE TITLE
SHA3 unsupported algorithm in some other runtimes

### ISSUE THREAD

**Issue by Khalid-Nowaf** [telegraf/telegraf#1879]
Telegraf is using SHA3 to hash secret, which broke my codebase after porting it to Bun instead of Nodejs.

Then, I dig deeper into SHA3 usage in the ecosystem in general, which seems like a drop-replacement for SHA2 if it is broken (future-proof), and I was surprised that many runtimes do not support SHA3. For instance,  Google/BoringSSL/Chrome might stand in the way because they might [skip SHA-3](https://www.imperialviolet.org/2017/05/31/skipsha3.html). See also https://github.com/w3c/webappsec-subresource-integrity/issues/11 and https://github.com/electron/electron/issues/30530.

I propose that Telegraf replace any use for SHA3 with SHA2 to make this framework compatible with other runtimes. We can return to SHA3 if there is a real need for it.

If the proposal is accepted, I would happily open PR for this issue.

**Comment by MKRhere** [comment]
I already ran into this problem in the v5 branch, because we use `crypto.createHash` synchronously, and `WebCrypto.subtle` is an async API. Although, now that I'm looking at it, we can probably remove using secretPathComponent in the path from [here (`Telegraf::getDomainOpts`)](https://github.com/telegraf/telegraf/blob/d30c62d8d09e9870c49217786d0594ee2d7408d1/src/telegraf.ts#L167), and instead create a default secretToken [here (`Telegraf::createWebhook`)](https://github.com/telegraf/telegraf/blob/d30c62d8d09e9870c49217786d0594ee2d7408d1/src/telegraf.ts#L188) and [here (`Telegraf::launch`)](https://github.com/telegraf/telegraf/blob/d30c62d8d09e9870c49217786d0594ee2d7408d1/src/telegraf.ts#L252). In both these places awaiting is okay.

This + modifying `Telegraf::secretPathComponent()` to async would be a breaking change, so would need to be PR'd to the v5 branch. (Ignore the type errors on v5 for now). While at it, might as well rename secretPathComponent to something more sensible to the new approach, like `generateTokenSecret()`.

Secret path component was Telegraf's way of adding a layer of security when Bot API didn't have one, but since then Bot API added the `secret` parameter.

I'll gladly accept a PR that implements these changes!

**Comment by MKRhere** [comment]
Update: you should actually PR the feat-deno branch which is ahead of v5, here: https://github.com/telegraf/telegraf/blob/feat-deno/src/platform/crypto.ts

**Comment by Khalid-Nowaf** [comment]
@MKRhere `feat-deno` is a platform-specific implementation (As far as I can tell); how a PR should solve the issue for another platform such as Bunjs?

**Comment by MKRhere** [comment]
Contrary to its name, feat-deno completely makes us platform-independent. Everything that's platform-specific to Deno has been moved into `src/platform`, which can be replaced by `platform.node`, `platform.web`, `platform.bun`, and so on (Deno just becomes the default because it's easier to build for other platforms from there).

So what I'm asking is more to implement hash using WebCrypto, and move it outside of platform to maybe `util.ts`, since all platforms support it. And make the necessary changes in `telegraf.ts`:

* Implement hash with WebCrypto
* Remove `Telegraf::secretPathComponent` call from `Telegraf::getTokenOpts`
* Rename `Telegraf::secretPathComponent` to `Telegraf::generateTokenSecret`
* Call `Telegraf::generateTokenSecret` in `Telegraf::createWebhook` and `Telegraf::launch`, pass the value as `secret`

Is that clearer?

**Comment by MKRhere** [comment]
Fixed in #1880 and #1881
