### ISSUE TITLE
Keyboard bot example produces Error: next(ctx) called with invalid context

### ISSUE THREAD

**Issue by mahnunchik** [telegraf/telegraf#223]
Hi,

[Keyboard bot](https://github.com/telegraf/telegraf/blob/develop/docs/examples/keyboard-bot.js#L66-L74) example:

```js
bot.command('random', (ctx) => {
  return ctx.reply('random example',
    Markup.inlineKeyboard([
      Markup.callbackButton('Coke', 'Coke'),
      Markup.callbackButton('Dr Pepper', 'Dr Pepper', Math.random() > 0.5),
      Markup.callbackButton('Pepsi', 'Pepsi')
    ]).extra()
  )
})
```

produces the following error:

```bash
Failed to process updates. Error: next(ctx) called with invalid context
    at execute (/test-telegram/node_modules/telegraf/composer.js:226:33)
    at Promise.resolve.handler (/test-telegram/node_modules/telegraf/composer.js:238:49)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

  Error: next(ctx) called with invalid context
      at execute (/test-telegram/node_modules/telegraf/composer.js:226:33)
      at Promise.resolve.handler (/test-telegram/node_modules/telegraf/composer.js:238:49)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)


  Error: 400: Bad Request: QUERY_ID_INVALID
      at buildPayload.then.then.then.then (/test-telegram/node_modules/telegraf/core/network/client.js:102:17)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by dotcypress** [comment]
Hey @mahnunchik 

Thank you for report 👍

**Comment by weijinnx** [comment]
Any updates?

**Comment by Filprots** [comment]
In my case that happened because i used module for my bot, that has its own Telegraf library in it's node_modules directory.
That module just exported the middleware to the main bot.

In composer.js there's a check:

`if (!(context instanceof Context)) {
          return Promise.reject(new Error('next(ctx) called with invalid context'))
        }`

It causes the problem, because at runtime telegraf creates an instance of TelegrafContext in the main bot. (It's in file context.js)
And composer in child module takes that class from the file in its own node_modules dir, but because it points not to object in memory that is bound with main bot context, check fails in my additional module.

Here's that problem described at stackoverflow https://stackoverflow.com/questions/46618852/require-and-instanceof

So the solution is to use peerDependencies

More about that https://nodejs.org/en/blog/npm/peer-dependencies/
