### ISSUE TITLE
Bots flip out on messaging users that block it

### ISSUE THREAD

**Issue by nnbosko** [telegraf/telegraf#38]
(node:3370) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 403: Forbidden: Bot was blocked by the user

  Error: 403: Forbidden: Bot was blocked by the user
      at TelegramError (/home/ubuntu/remmynbot/node_modules/telegraf/lib/network/error.js:3:5)
      at buildPayload.then.then.then.then (/home/ubuntu/remmynbot/node_modules/telegraf/lib/network/client.js:87:17)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by dotcypress** [comment]
[Error handling in Telegraf](http://telegraf.js.org/introduction.html#error-handling)

**Comment by underoot** [comment]
Problems may occurred when in middlewares put `next()` without return it. For example [in this gist](https://gist.github.com/underoot/4a7cd059b8ee5de283a0fe07562cae8f) error handler did not execute. [At this line of code](https://github.com/telegraf/telegraf/blob/develop/lib/core/composer.js#L162) Promise will be resolved without waiting execution other handlers when handler will be equal this handler with `next()` statement without return:

```javascript
app.use((ctx, next) => {
  next();
});
```

This can be fixed by using `return next()` statement:

```javascript
app.use((ctx, next) => {
  return next();
});
```

 It is normal? Why itis not mentioned at some part of documentation if is it?

**Comment by dotcypress** [comment]
Hey @underoot

Yes, it's normal behaviour and yes, i definitely need to update documentation.
Thank you 👍

**Comment by athimannil** [comment]
> [Error handling in Telegraf](http://telegraf.js.org/introduction.html#error-handling)

The link doesn't work :-(

**Comment by underoot** [comment]
@athimannil  Documentation updated. New link [here](https://telegraf.js.org/#/?id=error-handling)
