### ISSUE TITLE
ctx.reply() doesnt return data when using web hook

### ISSUE THREAD

**Issue by Daspharion** [telegraf/telegraf#420]
Is there a way to get `message_id` from a just sent message when using web hook?

**Comment by Otto-AA** [comment]
I fear that this is not possible with `ctx.reply`: 

> How can I make requests in response to updates?
This is possible if you‘re using webhooks. The upside is that you need less requests, the downside — that in this case it’s not possible to know that such a request was successful or get its result.

\- https://core.telegram.org/bots/faq#how-can-i-make-requests-in-response-to-updates


It _seems_ that the message id is always increased by one, so a kinda risky approach would be to take the message_id of the incoming request (ctx.message_id) and it increase it by one. Yet this could fail if the user writes another message instantly afterwards.
________________
However, you can use `bot.telegram.sendMessage(ctx.chat.id, 'Your response').then(sentMessage => {...})` instead of `ctx.reply`

For instance this:
```javascript
bot.command('test', ctx => {
  console.log(ctx.message.message_id);
  bot.telegram.sendMessage(ctx.chat.id, 'my response')
    .then(({ message_id }) => console.log(message_id))
    .catch(console.error);
});
```
logs `1122` (incoming message_id) and `1123` (outgoing message_id)

**Comment by Daspharion** [comment]
Ughhh.... webhook's response doesn't even have the `message_id` in it:
# CODE
```
Handler.command('test', ctx => {
  ctx.telegram.sendMessage(ctx.message.from.id, 'Test message')
    .then(data => console.log(data))
    .catch(err => console.error(err))
})
```
# RESPONSE
## Using polling
```
{ message_id: 7314,
from: {
id: 552890720,
is_bot: true,
first_name: 'DΞV\\\\PRΘFFΞSSΘR',
 username: 'devproffessorbot' },
chat: {
id: 335896744,
first_name: 'Daspharion',
username: 'Daspharion',
type: 'private' },
date: 1526327619,
text: 'Test message' 
}
```
## Using webhook
```
{ webhook: true,
details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
```

**Comment by Otto-AA** [comment]
Don't use `ctx.telegram.sendMessage` but `bot.telegram.sendMessage` (or with your namings it's probably `Handler.telegram.sendMessage`. Then it should work :)

**Comment by dotcypress** [comment]
Basically, `ctx.reply` is shortcut to `ctx.telegram.sendMessage`.
If you wanna disable response to webhook, you can use `ctx. webHookReply` prop:
```js
bot.command('test', ctx => {
  ctx.webHookReply = false
  // will use rest api for call
  ctx.telegram.sendMessage(ctx.message.from.id, 'Test message')
    .then(data => console.log(data))
    .catch(err => console.error(err))

  ctx.webHookReply = true
  // will use webhook response for call
  ctx.telegram.sendMessage(ctx.message.from.id, 'Test message2')
    .then(data => console.log(data))
    .catch(err => console.error(err))

})
```

**Comment by Daspharion** [comment]
Oh wow. Thank you so much for the support!
