### ISSUE TITLE
Telegraf Crashes When replyWithPhoto Is Used with Webhook

### ISSUE THREAD

**Issue by kotyagin** [telegraf/telegraf#440]
## Context

* Telegraf.js Version: 3.21.2
* Node.js Version: v10.3.0
* Operating System: Ubuntu 18.04 LTS

## Expected Behavior

I have a simple bot, which replies with image to any text received. Basically, everything it does is

```
bot.on('text', ctx => {
  ...
  ctx.replyWithPhoto({source: fs.createReadStream(somePath)}, {caption: someCaption})
  ...
})
```

Everything works just fine when the bot is configured to use polling, but crashes if I set up webhook.

## Current Behavior

When I configure the bot to use webhook, it crashes when I try to send a photo with ctx.replyWithPhoto. If I modify the code above to:

```
bot.on('text', ctx => {
  ...
  ctx.reply(someMessage)
  ctx.replyWithPhoto({source: fs.createReadStream(somePath)}, {caption: someCaption})
  ...
})
```

everything works. So basically, telegraf crashes when photo is being sent with answerToWebhook.

### Failure Logs

```
telegraf:client HTTP call setWebhook { url:
   'https://HOST/SECRETADDRESS' } +0ms
  telegraf:client Call via webhook sendPhoto { chat_id: 94968010,
  photo:
   { source:
      ReadStream {
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        path: '/tmp/tmp-8281XUbvvO3XH1A4.tmp',
        fd: null,
        flags: 'r',
        mode: 438,
        start: undefined,
        end: Infinity,
        autoClose: true,
        pos: undefined,
        bytesRead: 0,
        closed: false } },
  caption: 'test caption' } +3s
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:580:17)
    at ServerResponse.write (_http_outgoing.js:575:10)
    at MultipartStream.ondata (_stream_readable.js:672:20)
    at MultipartStream.emit (events.js:182:13)
    at MultipartStream.Readable.read (_stream_readable.js:492:10)
    at flow (_stream_readable.js:920:34)
    at resume_ (_stream_readable.js:902:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ServerResponse.onerror (_stream_readable.js:696:12)
    at ServerResponse.emit (events.js:182:13)
    at writeAfterEndNT (_http_outgoing.js:639:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by tva10** [comment]
Hello @kaliway, check #320 issue

When you use webhook, telegraf use `webhookReply` to answer by default. That hold http socket opened while your promise performed.

If you wanna make more replies, you should use Promise chaining, smth like `ctx.reply().then(() => ctx.reply()).then(()=> ctx.reply)...`
Or you can disable webhookReply in config: `new Telegraf(BOT_TOKEN, { webhookReply: false});`

**Comment by kaliway** [comment]
Thanks, but the thing is, I only have one reply in my code and telegraf crashes:

Basically, the following code crashes telegraf:

```
bot.on('text', ctx => {
  ctx.replyWithPhoto({source: fs.createReadStream(somePath)}, {caption: someCaption})
})
```

when webhookReply is true. I believe this is obviously a bug.

Surprisingly, if I use the following code:

```
bot.on('text', ctx => {
  ctx.reply(someMessage)
  ctx.replyWithPhoto({source: fs.createReadStream(somePath)}, {caption: someCaption})
})
```

Everything works fine, possibly because ctx.reply(someMessage) goes via webhookReply, while ctx.replyWithPhoto does not. I suspect uploading and sending photos via webhookReply is somehow broken.

By the way, I see no reason why I need to use promise chaining when sending multiple messages. If I don't mind the order, everything should work just fine is parallel.

**Comment by kaliway** [comment]
There is a complete script, which illustrates the problem:

```
'use strict';
const fs = require('fs')
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN, { webhookReply: false })
bot.telegram.setWebhook(WEBHOOK_ADDRESS)

bot.start((ctx) => {
  ctx.reply('Hi!')
})

bot.on('text', async (ctx) => {
  ctx.replyWithPhoto({source: fs.createReadStream('/some/existing/image.png')})
})

bot.startWebhook(WEBHOOK_ADDRESS, null, 5000)
```

When I send `/start` everything works just fine.
When I send any text, bot crashes with the following output:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:580:17)
    at ServerResponse.write (_http_outgoing.js:575:10)
    at MultipartStream.ondata (_stream_readable.js:672:20)
    at MultipartStream.emit (events.js:182:13)
    at MultipartStream.Readable.read (_stream_readable.js:492:10)
    at flow (_stream_readable.js:920:34)
    at resume_ (_stream_readable.js:902:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at writeAfterEndNT (_http_outgoing.js:639:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by tva10** [comment]
Hmm, if problem is in sending photo, try to don't use file stream
Mb you just need to specify path to image
check #395

**Comment by kaliway** [comment]
tva10 I appreciate your effort to help, but I am not really interested in finding a workaround for the problem. I filed this bug report just to let the community and the developers know that some pretty basic functionality is broken.

**Comment by kaliway** [comment]
OK, finally it looks like I found the cause for the issue.

The solution is to simply change the code:
```
bot.on('text', async (ctx) => {
  ctx.replyWithPhoto({source: fs.createReadStream('/some/existing/image.png')})
})
```

to:
```
bot.on('text', async (ctx) => {
  return ctx.replyWithPhoto({source: fs.createReadStream('/some/existing/image.png')})
})
```

There is a perfectly valid reason for this change, though. The code in `webhook.ls` expects a Promise. When the Promise is resolved, the response is ended. If `return` is omitted, no promise to wait is received and the response is ended before the response body is fully written.

Basically, the bug is in my code. However, I do think that there is a documentation issue. If you take a look at the Working with files section from which I copied the code, there is no return in the example there. On the other hand, return is used in other parts of documentation. So the documentation kinda sends mixed messages :) I believe it should be clearly stated somewhere in the documentation that using return is a must.
