### ISSUE TITLE
Error: 400: message text is empty. / Is it possible to return without a value?

### ISSUE THREAD

**Issue by saiij** [telegraf/telegraf#563]
I have the problem that I can't exit my function without a value.

This code:
```
...
Bot.command('roll', ctx => ctx.reply(roll(ctx)))

const roll = (ctx) => {
        if (muted === true){ 
            return;
        }
...
```

creates this error:
```
Error: 400: Bad Request: message text is empty

      at buildConfig.then.then.then.then (/rbd/pnpm-volume/6c441457-2914-4eb4-96d1-5779431ab406/node_modules/.registry.npmjs.org/telegraf/3.25.0/node_modules/telegraf/core/network/client.js:262:17)

      at process._tickCallback (internal/process/next_tick.js:68:7)


Failed to process updates. { Error: 400: Bad Request: message text is empty

    at buildConfig.then.then.then.then (/rbd/pnpm-volume/6c441457-2914-4eb4-96d1-5779431ab406/node_modules/.registry.npmjs.org/telegraf/3.25.0/node_modules/telegraf/core/network/client.js:262:17)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  code: 400,

  response:

   { ok: false,

     error_code: 400,

     description: 'Bad Request: message text is empty' },

  description: 'Bad Request: message text is empty',

  parameters: {},

  on: { method: 'sendMessage', payload: { chat_id: XXX } } }
```

Is it possible to exit the function without breaking the bot?

Edit: I already tried try and catch return 0, etc..

**Comment by tva10** [comment]
@saiij, Hello

Mb you should use promises there, something like this:

```javascript

Bot.command('roll', ctx => roll(ctx).then( text => ctx.reply(text), err => console.log(err) );
function roll(ctx) {
        // or return new Promise( function(resolve, reject){ .... } );

        if (muted === true){ 
            return Promise.reject();
        } else {
            return Promise.resolve('Some text');
        }
}

```

**Comment by tva10** [comment]
@saiij, In my example, I mean, that you can use your own Promise chain in command handler.

This warning happens because I did not added `.catch` block - 
```javascript
Bot.command('roll', ctx => roll(ctx).then( text => ctx.reply(text) ).catch( err => console.log(err) );
```
But your changes is not right way, yep, it did nothing - `return Promise.reject().catch(...);`. 
Pls check how promises works: [1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) [2](https://javascript.info/promise-basics). Because this lib is full of asynchronous methods and knowledge how they works will help you alot.
E.g. ctx.reply() returns a promise - and you can catch all errors wich happens there. - `ctx.reply(...).catch( err => { do smth } )`. Or can chain some replies `ctx.reply('1').then( _ => ctx.reply('2')).then(_=>ctx.reply('3'))` to send them in series

And also simple another way for you, I think, is adding ctx.reply inside your roll method

**Comment by tva10** [comment]
@saiij, I gave you an example withouth promises, there you run reply inside roll method...
If you want, I can answer more, if you write in me in telegram, because this doesn't look like Telegraf.js problem

**Comment by saiij** [comment]
Well I used another framework before there it wasn't a problem to return empty messages. But okay than let's talk about it on Telegram.

**Comment by wilsonpage** [comment]
What was the outcome here? I'm having an issue whereby messages are getting queued up from Telegram client if I don't explicitly reply But Im my case I only want to reply under certain conditions.
