### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by mishasbtr** [telegraf/telegraf#610]
After deployment to Heroku the bot receives all messages, but doesn't answer.
In case the bot sends two messages consequently in a short period of time, only the second one gets delivered.
When polling is used, all the messages sent by the bot get delivered. I also tried using webhooks without express, but nothing changed.
I found several related issues, but in all of them the author ended up using node-telegram-bot library which solved the problem.

The code used for setting webhook:
```js
const express = require("express");
const expressApp = express();

const bot = new Telegraf(process.env.BOT_TOKEN);
bot.telegram.setWebhook(`${process.env.BOT_URL}/bot${process.env.BOT_TOKEN}`);
expressApp.use(bot.webhookCallback(`/bot${process.env.BOT_TOKEN}`));

bot.use(Telegraf.log());
bot.use(session({
    ttl: 100
}));

expressApp.get("/", (req, res) => {
    res.send("Hello World!");
});
expressApp.listen(process.env.PORT, () => {
    console.log(`Example app listening on port ${process.env.PORT}!`);
});
```

**Comment by chakaponi** [comment]
In my case, only adding via ".launch" worked.  
`bot.launch({  
  webhook: {  
	domain: '______.herokuapp.com',  
	hookPath: '/RANDOM_ID',  
	port: process.env.PORT  
  }  
});`

**Comment by TorlanDelta** [comment]
> In my case, only adding via ".launch" worked.
> 
> ```js
> bot.launch({
>   webhook: {
> 	domain: '______.herokuapp.com',
> 	hookPath: '/RANDOM_ID',
> 	port: process.env.PORT
>   }
> });
> ```

Your solution results in "bot.launch is not a function". 

I also experience the same overall problem that really resembles connection issues, but I don't think it's that since I can see all my POST requests arriving to the bot via heroku log.

Bot decides to randomly skip instructions such as  deleting user messages, answering callback queries etc. etc. 

I will probably open my own issue for that though.

**Comment by TiagoDanin** [comment]
>Your solution results in "bot.launch is not a function".

Update Telegraf!

**Comment by TorlanDelta** [comment]
> > Your solution results in "bot.launch is not a function".
> 
> Update Telegraf!

Okay, that was my bad. But could you explain to me in which way do I use it? 

Right now I have a code like so: 

```
function setWebhook(){
  bot.telegram.setWebhook(`${URL}/bot${TOKEN}`)
  bot.launch({
    webhook: {
	     domain: 'mybotyay.herokuapp.com',
	      hookPath: '/RANDOM_ID', //LITERALLY THAT, I DUNNO WHAT IS RANDOM ID
	       port: PORT
       }
  })
  expressApp.use(bot.webhookCallback(`/bot${TOKEN}`))
  expressApp.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`)
  })
}

```

Results in `Error listen EADDRINUSE. 

So what do I remove? I am kinda confused xD

**Comment by TiagoDanin** [comment]
> Results in `Error listen EADDRINUSE.

Port is used by another application.
 
`index.express.js`
```js
const Telegraf = require('telegraf')
const express = require('express')
const expressApp = express()

const port = process.env.PORT || 5000 // Correct port will be returned here
const bot = new Telegraf(process.env.BOT_TOKEN)

expressApp.use(bot.webhookCallback('/secret-path'))
bot.telegram.setWebhook('https://MY-APP.heroku.com/secret-path')

expressApp.get('/', (req, res) => {
  res.send('Hello World!')
})

expressApp.listen(port, () => {
  console.log(`Example app listening on port ${port}!`)
})
```

NOTE (Server): `.launch` will create a new server.
NOTE (Security): Do not use token in secret path.

**Comment by TorlanDelta** [comment]
@TiagoDanin  This is not what I asked, although I do appreciate your effort. 

What I do struggle with is how to implement bot.launch in the code you provided yourself.

I have exactly the same setup with expessApp and stuff, so I was having trouble modifying my code to fit the bot.launch in. 

Also I updated the telegraf obviously and I am still experiencing random malfunctioning API calls.

What is skipped almost always is the calls of `ctx.telegram.deleteMessage()` and `ctx.answerCbQuery()`. 

`ctx.telegram.editMessageMedia()` seems to ALWAYS work though. 

I can post the whole code base of mine, but since its multiple files I do feel like it's too much to go through for you guys. The fact is that it's all working fine with locally hosted long polling app.

**Comment by stasusov** [comment]
After debugging I can claim it is related to `response.end()` called [here](https://github.com/telegraf/telegraf/blob/develop/core/network/client.js#L187), that is called [here](https://github.com/telegraf/telegraf/blob/develop/core/network/client.js#L239) in case of Webhook setup.

In express, it finishes the request processing, so no code after the first answer to the request (e.g. `ctx.reply` -> `sendMessage`) is executed.

It can be reproduced with express on localhost using ngrok.

Currently I have no idea what is the workaround for this case, but I believe we should find the fix and mention this in docs, because several issues were created related to this.

**Comment by stasusov** [comment]
New day and new discovery!

When `compression` express middleware is used, `response.end` gets overridden by [this](https://github.com/expressjs/compression/blob/master/index.js#L92) signature, that doesn't have a callback parameter. Therefore [this promise](https://github.com/telegraf/telegraf/blob/develop/core/network/client.js#L186) never resolves and execution stops.

If we do not use `compression`, bot works as expected and the same as with long polling set.

I found an issue an [old issue](https://github.com/expressjs/compression/issues/46) in the compression Github repo concerning adding the callback parameter, but it ended up in a [PR](https://github.com/expressjs/compression/pull/101) from 2017 that is not going to be merged.

What is more, there is [shrink-ray](https://www.npmjs.com/package/shrink-ray) that also can be used and behaves the same as `compression`.

What am I going to do is to submit a PR that simply checks the number of arguments for the `end` function and resolve the promise right after `end` if not callback is available. If you have better ideas, please share.

**Comment by coxato** [comment]
> > Results in `Error listen EADDRINUSE.
> 
> Port is used by another application.
> 
> `index.express.js`
> 
> ```js
> const Telegraf = require('telegraf')
> const express = require('express')
> const expressApp = express()
> 
> const port = process.env.PORT || 5000 // Correct port will be returned here
> const bot = new Telegraf(process.env.BOT_TOKEN)
> 
> expressApp.use(bot.webhookCallback('/secret-path'))
> bot.telegram.setWebhook('https://MY-APP.heroku.com/secret-path')
> 
> expressApp.get('/', (req, res) => {
>   res.send('Hello World!')
> })
> 
> expressApp.listen(port, () => {
>   console.log(`Example app listening on port ${port}!`)
> })
> ```
> 
> NOTE (Server): `.launch` will create a new server.
> NOTE (Security): Do not use token in secret path.

Hi, I have a question, what is `/secret-path` ?, What am I supposed to put there?
