### ISSUE TITLE
[QUESTION] How to make a transition to another scene when loading a document into a bot?

### ISSUE THREAD

**Issue by DevelooperQ** [telegraf/telegraf#747]
I can't do it, please help me

**Comment by twoperkg** [comment]
This code is taken from [https://github.com/telegraf/telegraf/blob/develop/docs/examples/scenes-bot.js](url)


// Greeter scene
const greeterScene = new Scene('greeter')
greeterScene.enter((ctx) => ctx.reply('Hi'))
greeterScene.leave((ctx) => ctx.reply('Bye, some have uploaded file!!!'))
greeterScene.hears('hi', enter('greeter'))
// On updateType 'document' enters echo scene
greeterScene.on('document', enter('echo'))


// Echo scene
const echoScene = new Scene('echo')
// Enters 'echo' scene and prints file name uploaded in 'greeterScene'
echoScene.enter((ctx) => ctx.reply(`Hello I entered from another scene, because was uploaded file: ${ctx.message.document.file_name}`))
echoScene.leave((ctx) => ctx.reply('exiting echo scene'))

**Comment by DevelooperQ** [comment]
Thank you
