### ISSUE TITLE
ContextMessageUpdate type definition missing 'session'

### ISSUE THREAD

**Issue by fsoft72** [telegraf/telegraf#914]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.34.1
* Node.js Version:  12.11.1
* Operating System:  Ubuntu Linux 19.10

## Expected Behavior

ContextMessageUpdate   type definition is missing 'session' attribute definition

## Current Behavior

When trying to access  ctx.session in TypeScript code generates an error

## Fix

Add:

`session: any `

in the ContextMessageUpdate definition  (use 'any' because the session can be augmented by user scripts)

**Comment by twoperkg** [comment]
I think you have to extend ContextMessageUpdate your self because session middleware is registered optionally.

interface MyContext extends ContextMessageUpdate {
    session: MySession
}
Define interface for you session, so you get code coplition for your properties. 
const bot =  new Telegraf<MyContext>(BOT_TOKEN)

**Comment by wojpawlik** [comment]
Modifications to context type done by middleware are difficult to type correctly.

**Comment by wojpawlik** [comment]
I think I figured it out, I'll add it when I'll be doing other TS stuff:

```ts
type MiddlewareExt<
  Ext extends object,
  BaseContext extends TelegrafContext = TelegrafContext
> = <TContext extends BaseContext>(
  ctx: TContext,
  next: (ctx: Ext & TContext) => Promise<void>
) => void | Promise<unknown>;

export declare function session<
  SessionData extends object,
  Prop extends string = "session"
>(opts?: {
  property?: Prop;
  store?: Map<string, { session: SessionData, expires?: number }>;
  getSessionKey?: (ctx: TContext) => string;
  ttl?: number;
}): MiddlewareExt<{ [Prop]: SessionData | {} }>;
```

...don't ask. Untested.

Still no idea how to make `Composer` deal with this little monster correctly.

**Comment by wojpawlik** [comment]
^ It's broken, it doesn't ensure that `next` is called.

**Comment by KnorpelSenf** [comment]
What @twoperkg says is correct and it also is the most elegant solution in many cases. Some session middleware allows the user to specify the property containing the session data, e.g. the context will be `ctx['my-session-property']` instead of `ctx.session`. As this string is only known at runtime, we cannot possibly type this correctly at compile time.

Instead of adding a potentially wrong property `session` to the context object (this could be done using [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)), it would make much more sense to provide better documentation so that new users know they need to add this property to their context type manually.
