### ISSUE TITLE
Why on webhook i'm send reply() and don't take correct result? How fix this?

### ISSUE THREAD

**Issue by MakStashkevich** [telegraf/telegraf#917]
### Failure Information (for bugs)

I run this code on webhook connection.
`ctx.reply(...data).then((result) => console.log(result))`

and get this:
`{
webhook: true,
details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
`

How fix this??

**Comment by mirismaili** [comment]
I encountered this issue too. I think this is due to Telegram API specifications, not this framework. But I only worked with Telegram API throw this framework and don't know the main API correctly.
I will post my experience in more detail, soon ...

**Comment by mirismaili** [comment]
Consider below simple example:
```js
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)

bot.command('start', async (ctx) => {
	console.log(await ctx.reply('message 1'))
	console.log(await ctx.reply('message 2'))
})

bot.launch()
```

After `/start` command will be logged:
```js
{
  message_id: 175,
  from: {
    ...
  },
  chat: {
    ...
  },
  ...
}
{
  message_id: 176,
  from: {
    ...
  },
  chat: {
    ...
  },
  ...
}
```

Now the same example in **webhook** mode:

```js
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)

bot.command('start', async (ctx) => {
	console.log(await ctx.reply('message 1'))
	console.log(await ctx.reply('message 2'))
})

bot.launch({
	webhook: {
		domain: process.env.REMOTE_HOST,
		port: process.env.PORT
	}
})
```

The log:
```js
{
  webhook: true,
  details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
{
  message_id: 178,
  from: {
    ...
  },
  chat: {
    ...
  },
  ...
}
```

Why the first log is:
```js
{
  webhook: true,
  details: 'https://core.telegram.org/bots/api#making-requests-when-getting-updates'
}
```

**Comment by mirismaili** [comment]
I found a solution. But _**I'm not sure this is the correct way or not**_! 
Anyway, **disable `webhookReply`** (`bot.telegram.webhookReply = false`):

```js
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)

bot.command('start', async (ctx) => {
	console.log(await ctx.reply('message 1'))
	console.log(await ctx.reply('message 2'))
})

bot.telegram.webhookReply = false
bot.launch({
	webhook: {
		domain: process.env.REMOTE_HOST,
		port: process.env.PORT
	}
})
```

**Comment by ailinykh** [comment]
Webhooks are designed to decrease load to telegram servers and to provide plain client-server communication between your server and telegram.
So in *request -> response* terms it means that you have request `/start` and you *response* to telegram with the first default *message 1*
```javascript
console.log(await ctx.reply('message 1'))
```
In that case telegram server __does not respond__ to you, because it's you the one who responses. So, to release the callback telegraf returns [WEBHOOK_REPLY_STUB](https://github.com/telegraf/telegraf/blob/develop/core/network/client.js#L44) as a `reply` invocation result.
```javascript
console.log(await ctx.reply('message 2'))
```
Second `reply` translates into api call and in that case you receiving response from telegram as you expect

When you setting `bot.telegram.webhookReply = false` telegraf turns off webhook responses (always responds with HTTP/200) and sends all requests through api call
